### ISSUE TITLE
error since update from 1.1.1 to 1.1.2

### ISSUE THREAD

**Issue by barbalex** [fmoo/react-typeahead#106]
I now get this message in the console:

    Warning: Failed propType: Invalid prop `customListComponent` supplied to `Typeahead`, expected a ReactElement. Check the render method of `Filter`

I'm rendering like this:

    return (
      <div id='filter'>
        <div style={{position: 'relative'}}>
          <Glyphicon
            glyph={'remove'}
            style={removeGlyphStyle}
            onClick={this.onClickEmptyFilterField}/>
          <Typeahead
            ref={'typeahead'}
            placeholder={'filtern'}
            maxVisible={10}
            options={options}
            filterOption={'label'}
            displayOption={'label'}
            onOptionSelected={this.onSelectObject}
            customClasses={{
              'input': ['form-control'],
              'results': ['list-group'],
              'listItem': ['list-group-item']
            }}/>
        </div>
      </div>
    )

Filtering works though.

**Comment by leecrossley** [comment]
I'm also seeing this warning

**Comment by fmoo** [comment]
@lPadier - this is related to your changes, any particular guidance on how to address this? (feel free to send me a PR).

**Comment by growlsworth** [comment]
same

**Comment by alanrubin** [comment]
Same here

**Comment by lPadier** [comment]
I've just checked the source for ReactTransitionGroup that takes a component as a Prop, and they use React.PropTypes.any

https://github.com/facebook/react/blob/master/src/addons/transitions/ReactTransitionGroup.js

**Comment by fmoo** [comment]
Should be fixed in 1.1.3; please retest.

**Comment by barbalex** [comment]
works, thanks a lot

**Comment by leecrossley** [comment]
I can confirm this fix works, thanks.
