### ISSUE TITLE
.hover class position not resetting correctly

### ISSUE THREAD

**Issue by barbalex** [fmoo/react-typeahead#107]
The first time you filter, there is no .hover class, until you press the down key. After you press the down arrow key once, the .hover class is positioned at the top li item.

Now hit the down arrow key three times > the .hover class is now at the fourth item. Just as expected.

Now empty the filter field and begin filtering again. Even while you enter characters (before hitting an arrow key) the .hover class is already positioned at the fourth item. When you hit the down arrow key, the .hover class moves down from the fourth to the fifth item.

I would expect it to behave like it did the first time.

**Comment by barbalex** [comment]
seems to me this is solved

**Comment by pjrharley** [comment]
This doesn't appear to be fixed at all in the latest version - the commit referenced above does seem to fix it but it's not been merged back into this repository.
