### ISSUE TITLE
dynamically updating typeahead options (data)

### ISSUE THREAD

**Issue by peacechen** [fmoo/react-typeahead#11]
For this use case, as the user enters text in the typeahead input box, the client code performs a REST call to the server to fetch potential matches from a database.  For instance, as the user types "John Doe", the typeahead results should dynamically update with each keystroke, first matching all names beginning with "John", then "John D", etc...  I've tried to bind the options to the state as such:

    <ReactTypeahead.Typeahead ref="NameTypeahead" placeholder="Name"
            defaultValue={this.state.name}
            options={this.state.typeaheadResults}
            onKeyDown={this.typeaheadInputChanged}
    />

Neither defaultValue nor options props change when the state changes.
The onKeyDown handler makes the REST call and a setState() when the results come back. This has no effect on the typeahead.  If I initialize state.typeaheadResults to ["test", "123"], for example, those typeahead results appear. They never change when the state changes.  I've poked around in the react-typeahead source and am lost.  Am I setting this up wrong?

**Comment by fmoo** [comment]
Ok, I landed acf88f477e130817f4b8b496239a4d14d1a24e98 which is a sort of combination of both approaches that seems to work.  Let me know what you think!
