### ISSUE TITLE
Mid sentence autocomplete.

### ISSUE THREAD

**Issue by mattvv** [fmoo/react-typeahead#134]
Hey guys,

Trying  to get a simple autocoplete going, and it's working well so far for results at the start of a sentence.
For example:

List: [ @matt, @all, @hello ]

If I type "@" then the whole list appears, if I type '@m' then @matt appears.
However If I type 'Hello @'. I want to display the whole list, to replace that last @. Like an autocomplete. Is there any way to enable this functionality?

**Comment by thehuey** [comment]
You're asking for a "Select All Matching" functionality?  You'd have to add
that as a custom option to the top and have a function to populate all
matches.

**Comment by mattvv** [comment]
Basically I want the same @ functionality in this comment box. Whenever i'm in the textbox here and you type @ it populates a typehead, like @thehuey . 

Currently with react typeahead it's only doing it if the @ is the first letter in the textarea

**Comment by fmoo** [comment]
Hey Matt.  It sounds like you want something more like how mentions work on Facebook and Twitter.

This typeahead is built as a general solution to support a single value typeahead entry (Typeahead) or a multi-value typeahead entry (Tokenizer).  Neither really supports intermixing tokens with text.

You could probably build what you want with pieces of this library, but this isn't functionality we support out of the box today.

**Comment by mattvv** [comment]
Thanks guys, No worries!
