### ISSUE TITLE
react-typeahead build errors after npm install

### ISSUE THREAD

**Issue by bernadetteguinan** [fmoo/react-typeahead#14]
Hello,

I installed react-typeahead with npm

    npm install react-typeahead

However, I get build errors:

    ERROR in ./~/react-typeahead/src/typeahead/index.js
    Module parse failed: /Users/bernadetteguinan/code/wwb-web-app/node_modules/react-   typeahead/src/typeahead/index.js Line 87: Unexpected token <
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <TypeaheadSelector
    |         ref="sel" options={ this.state.visible }
    |         onOptionSelected={ this._onOptionSelected }
     @ ./~/react-typeahead/src/react-typeahead.js 1:16-38

    ERROR in ./~/react-typeahead/src/tokenizer/index.js
    Module parse failed: /Users/bernadetteguinan/code/wwb-web-app/node_modules/react-    typeahead/src/tokenizer/index.js Line 52: Unexpected token <
    You may need an appropriate loader to handle this file type.
    |     var result = this.state.selected.map(function(selected) {
    |       return (
    |         <Token key={ selected } className={classList}
    |           onRemove={ this._removeTokenForValue }>
    |           { selected }
     @ ./~/react-typeahead/src/react-typeahead.js 2:16-38

Can anyone help ?? thanks

**Comment by FoxxMD** [comment]
Im facing the same problem :+1:

**Comment by fmoo** [comment]
@FoxxMD - what command are you using to perform the build?

**Comment by FoxxMD** [comment]
I'm using webpack with a loader configuration to pickup `.jsx` extensions using `jsx-loader`

```
{ test: /\.jsx$/, exclude: /node_modules/, loader: "jsx-loader?harmony" }
```

I'm actually trying to switch to babel-loader so I can use regular `.js` files with es6 features (and jsx) however I still run in to the problem of how to run react-typeahead through the right loader since it's in `node_modules`.

**Comment by fmoo** [comment]
@FoxxMD - sorry, I'm a total noob, I've only been exposed to browserify+reactify so far and have no idea how to get this working with webpack without breaking browserify.

Is there a way to support both?

**Comment by FoxxMD** [comment]
No worries I'm a beginner with this as well. I'm sure there is a way to support them all. I'll get back to you once I've found a solution.

**Comment by fmoo** [comment]
#49 should fix this
