### ISSUE TITLE
Tokenizer custom values send hidden inputs as "[Object object]"

### ISSUE THREAD

**Issue by rogeriotaques** [fmoo/react-typeahead#141]
It would be a lot useful if there is an option to customise the token output.

Now, whenever you select an item from result list, it creates a token tag which has a hidden input field. But, when using an option list of objects, this hidden field has its value set to [Object object].

Would be great if either we could customise the token output, adding or removing elements inside created tag, as well as to define which object property should be used as the hidden field's value.

**Comment by minyoung** [comment]
I have a pull request for this:
https://github.com/fmoo/react-typeahead/pull/168

**Comment by fmoo** [comment]
Should be fixed.
