### ISSUE TITLE
How can i use fork

### ISSUE THREAD

**Issue by igoldny** [fmoo/react-typeahead#159]
I forked this project to make some changes but before i send you working pull request i want to use it in my project. 
But when i add to package.json "react-typeahead": "git@repo" i get error from webpack that lib is missing, now i see that lib created on npm publish which not been called for my fork.
what am i doing wrong and how can i make it work?
thnx

**Comment by fmoo** [comment]
Hi @igoldny - did you figure it out?  I think you have to run `npm run lib` before calling `npm install /path/to/react-typeahead-git/` from the repository where you want to use it.

**Comment by igoldny** [comment]
No I didn't, I just removed lib from gitignore which I see that most of the forks here did.
I don't want to add any extra scripts to my work flow nor my CI servers.
