### ISSUE TITLE
Visible list is populated when it should be empty

### ISSUE THREAD

**Issue by nosilleg** [fmoo/react-typeahead#162]
I discovered that if I hit start typing a string that has multiple matches and then hit tab very quickly I can get two tokens to render instead of the expected one.

I output some console log to trace this and I've annotated the results below.

![react-typeahead_debug_console](https://cloud.githubusercontent.com/assets/900365/13638032/4e0110f8-e602-11e5-80d8-d8a186b49b77.png)

PR incoming.

**Comment by fmoo** [comment]
Fixed in 1.1.6
