### ISSUE TITLE
use of React.__spread

### ISSUE THREAD

**Issue by VinSpee** [fmoo/react-typeahead#172]
It seems as though `React.__spread` is a private method, any reason you're using it instead of an Object spread polyfill or something similar?

https://github.com/facebook/react/blob/6a8ebfc41842fb200c87a919478dcd3aa95be0d7/src/isomorphic/React.js#L70

**Comment by fmoo** [comment]
No good reason afaik.  Please send a PR and ill merge it ASAP.

**Comment by VinSpee** [comment]
looks like it's in the `dist` directory, so it's likely react using it in a non-JSX version - my bad!

**Comment by fmoo** [comment]
Turns out there was actually something screwed up.  Should be fixed in 1.1.9
