### ISSUE TITLE
please support React 15.0.0

### ISSUE THREAD

**Issue by bob76828** [fmoo/react-typeahead#178]
I got the error that "Uncaught TypeError: React.__spread is not a function" on 15.0.0. It seems like the private method is removed.

https://github.com/facebook/react/commit/a142fd257803a218b5b9b2e76c327f0421b9b8b6

**Comment by bob76828** [comment]
I found what the problem is gulp-react uses the private method and it is deprecated. Maybe you should use gulp-babel to precompile jsx.

**Comment by tanepiper** [comment]
Hitting this issue to with upgrading from React-15.0.0-rc2 to React15 as well

**Comment by fmoo** [comment]
Is this a matter of bumping the devDependencies and republishing?

**Comment by fmoo** [comment]
Fixed in 1.1.9 .

I replaced gulp-react with gulp-babel and reactify with babelify.

**Comment by export-mike** [comment]
regarding warnings: https://github.com/fmoo/react-typeahead/pull/183
