### ISSUE TITLE
Ability to pass custom prop to customListComponent

### ISSUE THREAD

**Issue by localjo** [fmoo/react-typeahead#182]
We want the ability to pass an `href` value along with the options into our `customListComponent`. The idea is to make the options that display directly clickable. I was able to achieve this by adding a rider object inside the `customClasses` prop;

`customClasses={{menuItems: props.items, input: 'context-menu__search'}}`

This works, without warnings, but it would be nice if there was either a prop like `customData` that could be used to pass in objects like this, or if the `options` prop supported more than just an array of strings.

I'm mostly worried that, since my approach is a bit of a hack of the `customClasses` prop, that it might break in future minor versions.

**Comment by jigar1101** [comment]
@localjo Did you find a way to pass props to customListComponent?
