### ISSUE TITLE
showOptionsWhenEmpty using Tokenizer

### ISSUE THREAD

**Issue by jkindness** [fmoo/react-typeahead#199]
It looks like showOptionsWhenEmpty only works with Typeahead.

I'm using version 2.0.0-alpha.4 and setting showOptionsWhenEmpty to true works as expected when using Typeahead but not with Tokenizer.

**Comment by charlesbdudley** [comment]
I've created a PR for this issue here: https://github.com/fmoo/react-typeahead/pull/244

**Comment by fmoo** [comment]
Fixed in react-typeahead@2.0.0-alpha.8
