### ISSUE TITLE
typeahead, L121,  return result = searchOptions(value, options);

### ISSUE THREAD

**Issue by export-mike** [fmoo/react-typeahead#200]
```return result = searchOptions(value, options);```

https://github.com/fmoo/react-typeahead/blob/master/src/typeahead/index.js#L121

Any ideas what this is for? Looks like a bug to me. 

I've been getting errors for result is not defined

**Comment by fmoo** [comment]
my guess is this was a badly refactored debug assignment or something.  I merged the fix Will do a .5 release soon.
