### ISSUE TITLE
Tag 2.0.0-alpha.5 in github.

### ISSUE THREAD

**Issue by bmac** [fmoo/react-typeahead#216]
Hello. 

[NPM claims](https://www.npmjs.com/package/react-typeahead) the latest release is 2.0.0-alpha.5. I'd like to upgrade to this version however it doesn't look like that release is tagged on github which makes it difficult to generate a diff and inspect the changes.
Example diff: https://github.com/fmoo/react-typeahead/compare/1.1.9...2.0.0-alpha.4

Would it be possible for you to tag the 2.0.0-alpha.5 release and push the tag up to github? 

Thanks.

**Comment by fmoo** [comment]
crap.  fixed now.
