### ISSUE TITLE
Support render children props

### ISSUE THREAD

**Issue by bob76828** [fmoo/react-typeahead#217]
I want to add a add-ons icon to input element.
It's the bootstrap example.

`<div class="input-group">
  <span class="input-group-addon" id="basic-addon1">@</span>
  <input type="text" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
</div>`

**Comment by stavlocker** [comment]
I'm pretty sure this is already implemented. Have you tried the [`customListComponent`](https://github.com/fmoo/react-typeahead#propscustomlistcomponent) prop?
