### ISSUE TITLE
Include `package.json`

### ISSUE THREAD

**Issue by jordwalke** [fmoo/react-typeahead#3]
People should be able to use this from https://github.com/facebook/react-page as long as there is a `package.json` file. This could be one of the first "shared" components that we use as an example if you like. 

You can also define your CSS rules using JS directly using what Hedger built:
https://github.com/hedgerwang/react-styles.

That way, everything your component needs is completely encapsulated in a single github repo, and dependencies are modeled correctly using `package.json` files.

**Comment by cgarvis** [comment]
Can you make the `main` change suggested by @jordwalke.  Just ran into this when using it with webpack.

**Comment by fmoo** [comment]
@cgarvis - what change?  `main` is already set to `src/react-typeahead.js`

**Comment by cgarvis** [comment]
Sorry read wrong. I think what you want is `main` set to `dist/react-typeahead`.
