### ISSUE TITLE
Using <tab> to select with allowCustomValues results in `undefined` selection 

### ISSUE THREAD

**Issue by fmoo** [fmoo/react-typeahead#41]
## Repro Steps

1. Load the `typeahead-topcoat.html` example
2. Type `abcd` into the text entry
3. Press `<tab>`

## What should happen:
`abcd` gets selected

## What actually happens:
`undefined` gets selected.

**Comment by fmoo** [comment]
cc @wookiehangover, @thehuey since you both worked on stuff related to this.

**Comment by fmoo** [comment]
@thehuey - I also noticed the email address you've got configured for your git commits was a system default and (can't be? or) wasn't associated with your github account.  Can you try adding it (hueyhu@Hueys-Macintosh.local) to github or updating your real email address with `git config --global user.email YOUR_EMAIL` so your commits can get tied to your account?

**Comment by thehuey** [comment]
Thanks. I'll do that and look at the undefined issue later tonight

**Comment by thehuey** [comment]
This problem actually comes from the Typeahead selection and is unrelated to the Custom Values.  The _onTab function blindly assumes that there is a visible option.

I've fixed the issue and will be submitting a pull request shortly.  Proper tests have been added to verify the issue.

**Comment by fmoo** [comment]
When I disabled customValues, I couldn't repro the issue.  Thanks for fixing this!

**Comment by Rodeoclash** [comment]
I'm not really a fan of the tab selecting the option. To me, enter should select the highlighted option and tab should either not do anything or abandon the control and move to the next one. This behaviour would then match the behaviour of a native select box in the browser.

**Comment by fmoo** [comment]
@Rodeoclash - if you want to PR me a diff to add a boolean select-on-tab option (default false), I can pick it up and do a minor release.
