### ISSUE TITLE
no window on serve side

### ISSUE THREAD

**Issue by tcurdt** [fmoo/react-typeahead#48]
For example

  https://github.com/fmoo/react-typeahead/blob/master/src/typeahead/index.js#L5

creates a dependency to `window` prevents server side rendering as is (unless working around it by declaring it as {}).

**Comment by fmoo** [comment]
Oh nasty.  I think this is some leftover stuff from before we used browserify.

Should be safe to remove.  Want to send a PR?

**Comment by rhalff** [comment]
Hi, I've run into the same issue.

I've added a pull request  #55 to address it.

It was not safe to just remove the check though, because the generated dist file will be unable to find window.React, I've added a transform to the build script which fixes that issue.

This restores the old behavior, there are probably more complete solutions, but this one seems to work for now.

**Comment by fmoo** [comment]
> It was not safe to just remove the check though, because the generated dist file will be unable to find window.React, I've added a transform to the build script which fixes that issue.

Do you know if this was broken for both webpack and browserify?  Or just the later?

**Comment by rhalff** [comment]
Browserify & webpack will just work they do not need the window.React test.

The examples broke because they rely on window.React.

In short:
  - I've removed all window.React's from the source
  - changed the build script so the dist file *does* generate a version which tests for window.React

**Comment by fmoo** [comment]
K, this is merged.  Do you need a 1.0.3 release for this?  Or is this mainly for source distributions?

**Comment by rhalff** [comment]
Thanks, it does need a new release. Projects depending on react-typeahead will then have serverside rendering fixed.

**Comment by fmoo** [comment]
@rhalff - got it.  I cut a 1.0.3 release with just this change.  Thanks for contributing!
