### ISSUE TITLE
TypeError: Cannot read property '__reactAutoBindMap' of undefined

### ISSUE THREAD

**Issue by yujinlim** [fmoo/react-typeahead#56]
Hi, 

I was trying to use the Typeahead component with the latest v1.0.3 and I got this error,  `TypeError: Cannot read property '__reactAutoBindMap' of undefined`.I believe this have to do with how Typeahead components are compile via `gulp-react`, related [https://github.com/facebook/react/issues/2661](https://github.com/facebook/react/issues/2661). 

Thanks

**Comment by fmoo** [comment]
I'm having trouble reproducing this.  Can you provide more detailed repro steps?

**Comment by seansfkelley** [comment]
I was seeing this too. The bug seems to be from mixing 0.12 (which is what I was using) and 0.13 (which is what react-typeahead is using). I fixed mine by upgrading.

Nothing in the [changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md) jumps out at me except perhaps:

> Deprecated patterns that warned in 0.12 no longer work: most prominently, calling component classes without using JSX or React.createElement and using non-component functions with JSX or createElement

**Comment by yujinlim** [comment]
I solved it by removing `React` from react-typeahead folder, perhaps you need to use (http://blog.nodejs.org/2013/02/07/peer-dependencies/](peerDependencies)

**Comment by fmoo** [comment]
@yujinlim - Ok I set peerDependencies to >= 0.13.0 and released 1.0.4 (59544173cdd83a1d798ddca4e1432d1f2e52194c).  Let me know if that works for you!

**Comment by yujinlim** [comment]
@fmoo aite! thanks
