### ISSUE TITLE
Possibly adding lib folder to the repository

### ISSUE THREAD

**Issue by yujinlim** [fmoo/react-typeahead#63]
Hi, 

I was thinking is it possible to add lib folder to the repository. As you know, using npm, we can install packages from the git repo itself and I wanted to use latest version of the component without waiting for the release but currently, if I install it from the git repo, it will not able to run properly as its start up file is reference to `/lib` folder. 

check https://github.com/fmoo/react-typeahead/blob/master/package.json#L41

Thanks

**Comment by seansfkelley** [comment]
I was thinking of doing this too, in the context of #62, obnoxious though it is in terms of having to rerun the build and check in compiled resources (though if it's already happening for the dist file...).

**Comment by fmoo** [comment]
I've been pretty good about publishing changes directly to npm, and would like to try this for a while.  If a feature is on master that you need, please open an issue ASAP.

If it's not working out, feel free to reopen this or a new task and we'll revisit.
