### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by franleplant** [fmoo/react-typeahead#65]
Hi!
    It took me a while to find out how to use the Typeahead component.
Is there a particular reason to display the example as this (current doc):

```javascript
React.render(Typeahead({
  options: ['John', 'Paul', 'George', 'Ringo'],
  maxVisible: 2
}));
```

instead of this (as I actually got to make it work with other components):

```javascript
<Typeahead
  options={ ['John', 'Paul', 'George', 'Ringo']}
  maxVisible={2}
/>
```

Thanks!

Fran

**Comment by fmoo** [comment]
Nope.  The latter should be preferred.  Please feel free to send a PR updating the docs!

**Comment by franleplant** [comment]
Im doing the PR, a question first:

The component form should be wrapped in the `React.render` call right? Just to double check.

Something like this:

```javascript
React.render(<Typeahead
  options={ ['John', 'Paul', 'George', 'Ringo']}
  maxVisible={2}
/>)
```

**Comment by franleplant** [comment]
Created a PR https://github.com/fmoo/react-typeahead/pull/67
