### ISSUE TITLE
Asynchronously get the option list

### ISSUE THREAD

**Issue by franleplant** [fmoo/react-typeahead#66]
How can implement react-typeahead if the options are brought from the server asynchronously?

Thanks!
Fran

**Comment by fmoo** [comment]
In you've got a wrapper component, in its render method, just re-render the Typeahead with an updated `options` prop.

If the Typeahead is a top level component, use [`react.render`](https://facebook.github.io/react/docs/top-level-api.html#react.render)

**Comment by franleplant** [comment]
Yes, that was the way I ended up doing it, thanks a lot for your quick response.
Fran
