### ISSUE TITLE
Invariant Violation: addComponentAsRefTo(...)...

### ISSUE THREAD

**Issue by checkhavoc** [fmoo/react-typeahead#69]
After requiring and adding the Typeahead, I'm running into the following error:

Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

I'm adding the component as so:

`var QuickSearch = React.createClass({`
  `render: function () {`
    `return(`
      `<Typeahead options={["spam", "foodbar"]}/>`
     ` );`
  `}`
`});`

Then making a reference to it in another class:

`var Topbar = React.createClass({`
  `render: function() {`
   `return (`
          `<QuickSearch />`
    `);`
  `}`
`});`

This is essentially leading to the typeahead providing a new error when inputting values into the "entry" ref: 

Uncaught TypeError: Cannot read property 'getDOMNode' of undefined

Any help or suggestions would greatly be appreciated, thanks!

**Comment by thehuey** [comment]
Check your React version and perhaps do a "npm update". Also check how your TopBar is being rendered.  It needs to be used in a render function of some other container.

**Comment by checkhavoc** [comment]
Currently using:
React 0.13.2
Node 0.12.2
Npm 2.7.4

Yes, I'm requiring my TopBar in another component (different .jsx file) like so:

`var Topbar = require('./topbar');`
`var App = React.createClass({`
`render: function () {`
`return(`
`<div>`
`<Topbar />`
`</div>`
`)`
`}`
`});`

Still researching, but if anyone discovers a solution, let me know. Thanks!

**Comment by checkhavoc** [comment]
The issue was that the project was not using react/addons. After implementing react/addons, that fixed the problem

**Comment by Anenth** [comment]
`react/addons` is deprecated! why we using that?

**Comment by Anenth** [comment]
am having the same issue, i couldn't find a fix it.

**Comment by fmoo** [comment]
Have you tried switching to the 2.0.0-alpha.1 release yet?  I was hoping to get some more breaking changes in but with everyone wanting react 15, I should probably just push those to 3.0
