### ISSUE TITLE
Allow react elements as children for TypeaheadOption and Token

### ISSUE THREAD

**Issue by jbruggem** [fmoo/react-typeahead#76]
Using objects rather than strings as entries is useful if the options must have custom visualisations (for example: a user with his profile picture, a document title with a description, etc).

It seems react-typeahead works well when the supplied option is a react class rather than a string, except for the warnings because the type of children should be React.PropTypes.string. 

A simple fix would be to not set the allowed type of children. You would also need to change the way the element keys are built (use element.key if element is a react component).

Thanks for this awesome lib :)

**Comment by fmoo** [comment]
I think 1.0.8 addresses this by adding support for objects as options.  Let me know!

**Comment by jbruggem** [comment]
Hi fmoo,

It most probably solves the problem. I ended up integrating twitter-typeahead in the mean time but I'll definitely come back to this project next time I need this kind of feature!

I think we can close this for now.
