### ISSUE TITLE
how to get selection with down arrow key working

### ISSUE THREAD

**Issue by barbalex** [fmoo/react-typeahead#85]
First of all: thanks for this great tool. In my App I load 50'000 options and react-typeahead works BLAZING fast!

Also: Sorry for asking this here. There is (almost) no mention of react-bootstrap on stackoverflow yet.

I want the user to be able to choose an option (after having entered some letters) by navigating down with the down arrow key, then choosing it with the Enter key.

This works in the examples you provide.

I found nothing in the docs about how to achieve this though. And in my app it does not work.

I am instantiating it like this:

    const filter = (
      <Typeahead
        placeholder={'filtern'}
        maxVisible={10}
        options={options}
        filterOption={'label'}
        displayOption={'label'}
        onOptionSelected={this.filter}
        customClasses={{
          'input': ['form-control'],
          'results': ['list-group'],
          'listItem': ['list-group-item']
        }}/>
    )

    const nothing = <div/>

    return (
      <div id='filter'>
        {this.state.loading ? nothing : filter}
      </div>
    )

The custom classes are for twitter bootstrap.

**Comment by fmoo** [comment]
That's really weird, I could have sworn this behavior was previously implemented.

**Comment by barbalex** [comment]
well, be warned, I am a bad noob so it's probably just a dumb mistake of mine

**Comment by NerdCowboy** [comment]
It's not working for me either. I'm a noob as well, so possible I'm also doing something wrong, but I've tried to barebone it down as much as possible and I can't get it to work.

**Comment by rgoldfinger** [comment]
I had the same problem, but realized that it is working. It seems that it applies a `hover` class to the selected `<li>`, but I wasn't providing any styling for `hover`. Adding a `background-color` to `hover` fixed it for me.

**Comment by NerdCowboy** [comment]
Thanks @rgoldfinger, that worked for me :+1:

**Comment by fmoo** [comment]
Anything recommendations for things that might work better than just adding a class?  Either in code or in JavaScript?

Maybe we should be setting tabindex="0" to at least make it tabbable?

**Comment by NerdCowboy** [comment]
I think the way it works is good, I just didn't see any documentation on it, so I was confused. If you look at how Google does their auto-suggest, they also just add a class and fill the input when you press the `enter` key. 

I'm not sure what you mean by making it tabbable though. It feels right to me if you have an item "hovered" to allow a user to hit `enter` or `tab` to select the item as it's currently implemented. However, it currently breaks accessibility by not allowing a user to continue through the tabindex once you've brought the typeahead input into focus. 

So to fix the accessibility aspect, you could either allow a user to continue through the tabindex if they hit tab twice with or without selecting anything or you could copy the way Google does it—when you navigate through the list with the arrow keys, the input would be automatically filled with the currently highlighted item and hitting enter would verify the selection of the hovered item. The `tab` key would then become irrelevant unless you also do what Google does and auto-prefill the input with grayed out text and hitting `tab` would then select the gray text that's being suggested (which would be the first matching item in the list)

**Comment by barbalex** [comment]
yep, adding a class for .hover works for me too

What seems unexpected behaviour though is that the second time I filter, the .hover class is initially set at the item that is at the position where the last item containing it was located. I'd expect it to initially be included at the first item, like it is when you filter for the first time.

Anyway, this is no bug and the main issue seems solved so I'm closing this issue.

**Comment by fmoo** [comment]
Can you file a separate issue for the .hover class position not resetting correctly?  That's definitely a bug.

**Comment by barbalex** [comment]
done: https://github.com/fmoo/react-typeahead/issues/107
