### ISSUE TITLE
Add id and name field to the typeahead, tokenizer 

### ISSUE THREAD

**Issue by gauravtiwari** [fmoo/react-typeahead#9]
Hey there,

Thanks for this component. Works great. If  you can please let me know, how to add id and name attribute on input field?

Thank you,
Gaurav

**Comment by fmoo** [comment]
Does anyone still need this feature?  I can't believe I never got a PR for this (and that I never implemented this to begin with!)

**Comment by nemoo** [comment]
I think this is an important feature. The more generic approach is probably to implement this properly, dont you think?:  https://github.com/fmoo/react-typeahead/issues/40

**Comment by raysuelzer** [comment]
@nemoo  -- I'm not sure I understand your comment.

**Comment by nemoo** [comment]
Please forget my comment.

**Comment by fmoo** [comment]
I think I'm going to close this out.  `id` generally isn't something you should be worrying about with react.  If you need to access the state of the components and things, you should be doing this in react with native accessors and refs and things, not by accessing random parts of the DOM with javascript.

`name` is still useful if you want to use react-based components on legacy html forms, and that is now done on both the typeahead and the tokenizer.
