### ISSUE TITLE
Default classes conflict with several CSS Libraries

### ISSUE THREAD

**Issue by lPadier** [fmoo/react-typeahead#91]
It is only possible to add classes to elements, and it is not possible to remove the default classNames.
Should a prop allow default classNames to be removed?

**Comment by fmoo** [comment]
Is there a more compatible way to define default classes without getting rid of them entirely?

A prop to remove classes by default could be good.

**Comment by lPadier** [comment]
After checking, it appears I was confused. while the docs for Bootstrap 2 do use `.typeahead` in an example, it seems that there is no typeahead class by default.

However, in a large project I'm working on, the typeahead class is already used.

A prop such as defaultClassNames could work.

As far as how it could work in the library, it could be set to have a default value of true, and update classNames from 
```javascript
var classes = {
  typeahead: true
};
```
to :
```javascript
var classes = {
  typeahead: this.props.defaultClassNames
};
```
