### ISSUE TITLE
how to set inputProps

### ISSUE THREAD

**Issue by barbalex** [fmoo/react-typeahead#96]
Noob alarm: this issue is probably only due to my not understanding React or react-typeahead yet. If so, sorry for pestering you issues list.

I am trying to control the content of the typeahead input, for instance:

- empty it when a user clicks on an "X" symbol (see other issue: https://github.com/fmoo/react-typeahead/issues/86)
- empty it when a user navigates to a different option using the nav menu instead of the typeahead

My idea was to incorporate the selected option in state. When the typeahead input should empty, I would pass it's inputProps an apropriate option (I am not 100% sure what this option would look like though).

My options are built like this example:

    {
      'value': 'A7EDF4A9-9501-46A0-82E1-51CC567EC83F',
      'label': 'Clematis recta L. (Aufrechte Waldrebe)'
    }

To see if this basically works, I tested if I could pass a specific option via inputProps like this:

    getInitialState () {
      return {
        itemFiltered: {
          'value': 'A7EDF4A9-9501-46A0-82E1-51CC567EC83F',
          'label': 'Clematis recta L. (Aufrechte Waldrebe)'
        }
      }
    }

and inside render:

    const { itemFiltered } = this.state

    (some code constructing options from props and removeGlyphStyle)

    return (
      <div id='filter'>
        <div style={{position: 'relative'}}>
          <Glyphicon
            glyph={'remove'}
            style={removeGlyphStyle}
            onClick={this.onClickEmptyFilterField}
          />
          <Typeahead
            inputProps={itemFiltered}
            options={options}
            filterOption={'label'}
            displayOption={'label'}
            onOptionSelected={this.onSelectObject}
          />
        </div>
      </div>
    )

Unfortunately the passed in option does not appear in the typeahead input.

What am I doing wrong?

**Comment by miu-zsolt** [comment]
I can confirm, that passing values to inputProps doesn't work for me. Could you please fix it?

**Comment by csk157** [comment]
`value` prop is accepted by TypeaheadComponent itself

```javascript
<Typeahead
  inputProps={{name: "q", autoComplete: "off"}}
  onOptionSelected={this.handleOptionSelected}
  ref="typeahead"
  value="abcd"
   ....
```

**Comment by barbalex** [comment]
that only works on first load for me


2015-08-25 22:53 GMT+02:00 Ceslovas Lopan <notifications@github.com>:

**Comment by aganglada** [comment]
I'm loading Typeahead with inputProps in a modal and it doesn't look like working.

```
<Typeahead
    options={['John', 'Paul', 'George', 'Ringo']}
    maxVisible={5}
    placeholder="Add game"
    inputProps={{ ref: 'peopleName' }}
    customClasses={{
         input: 'people-name'
     }}
/>
```

Do I miss something?

FYI @fmoo

**Comment by barbalex** [comment]
I found this solution to empty the typeahead in a different issue:

    this.refs.typeahead.setState({
      entryValue: '',
      selection: null,
      selectionIndex: null,
      visible: []
    })

**Comment by skanel** [comment]
@aganglada  change `ref` to `Ref` with uppercase
