### ISSUE TITLE
Replace gulp-react with gulp-babel

### ISSUE THREAD

**Issue by lPadier** [fmoo/react-typeahead#98]
Facebook is deprecating jstransform and react tools in favor of babel:

https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

**Comment by jmesquita** [comment]
@fmoo, I can create a PR for this. Is this still of interest?

**Comment by fmoo** [comment]
Yeah, this is still interesting; gulp-react is deprecated.
